# ─── Datasource ───────────────────────────────────────────────────────────────
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:nounou_db_user}
quarkus.datasource.password=${DB_PASSWORD:nounou}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/nounou_db}

# drop-and-create only in dev — use 'validate' or 'update' for production
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%prod.quarkus.hibernate-orm.database.generation=validate

# ─── Jackson ──────────────────────────────────────────────────────────────────
quarkus.jackson.write-dates-as-timestamps=false

# ─── Mailer ───────────────────────────────────────────────────────────────────
quarkus.mailer.from=noreply@nounou-times.com
quarkus.mailer.host=${MAIL_HOST:smtp.example.com}
quarkus.mailer.port=${MAIL_PORT:587}
quarkus.mailer.ssl=false
quarkus.mailer.username=${MAIL_USERNAME:your-username}
quarkus.mailer.password=${MAIL_PASSWORD:your-password}
quarkus.mailer.auth-methods=DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN

# emails not sent in dev
%dev.quarkus.mailer.mock=true

# ─── OpenAPI ──────────────────────────────────────────────────────────────────
quarkus.swagger-ui.always-include=true
